[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.branch-deploy]
  [context.branch-deploy.environment]
    VUE_APP_MODE = "staging"

[context.deploy-preview]
  [context.deploy-preview.environment]
    VUE_APP_MODE = "staging"

[context.production]
  [context.production.environment]
    VUE_APP_MODE = "production"
